[package]
name = "church"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leb128 = "0.2.5"
pest = "2.0"
pest_derive = "2.0"
wasm-encoder = "0.24.1"

[scripts]
hello = "echo hello"
